Update nodeX container file
Based on latest changes
This resolves #226

qm.service failes to load
ignoring: unsupported key 'SecurityLabelNested' in group 'Container'

Signed-off-by: Yariv Rachmani <yrachman@redhat.com>

diff --git a/tests/e2e/lib/container b/tests/e2e/lib/container
--- a/tests/e2e/lib/container
+++ b/tests/e2e/lib/container
@@ -101,7 +101,7 @@ create_qm_node() {
         echo "RUN dnf install qm -y &> /dev/null" >> ContainerFile.node"${nodeID}"
 
         # Execute qm setup
-        echo "RUN /usr/share/qm/setup 2>&1 > /tmp/qm-setup.log || echo "QM setup failed, please check /tmp/qm-setup.log."" >> ContainerFile.node"${nodeID}"
+        echo "RUN /usr/share/qm/setup --skip-systemctl true 2>&1 > /tmp/qm-setup.log || echo "QM setup failed, please check /tmp/qm-setup.log."" >> ContainerFile.node"${nodeID}"
 
         # HACK: add /dev/fuse to qm.container. It will allow a container set limits inside
         # another container.
